name: CI Workflow

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

  code-quality-check:
    name: Code Quality and Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  enforce-branch-naming:
    name: Enforce Branch Naming Convention
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^(feature|bugfix|hotfix)/ ]]; then
            echo "Branch naming convention not followed. Branch name must start with 'feature/', 'bugfix/', or 'hotfix/'."
            exit 1
          fi
