name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Using Node.js version 20.x

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm test

  code-quality-check:
    name: Code Quality and Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  enforce-branch-naming:
    name: Enforce Branch Naming Convention
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^(feature|bugfix|hotfix)/ ]]; then
            echo "Branch naming convention not followed. Branch name must start with 'feature/', 'bugfix/', or 'hotfix/'."
            exit 1
          fi

  enforce-commit-message:
    name: Enforce Commit Message Format
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message
        run: |
          if [[ ! "$(git log --format=%s --no-merges -1)" =~ ^[A-Z].* ]]; then
            echo "Commit message format not followed. The first letter of the commit message must be capitalized."
            exit 1
          fi
  branch-protection:
    name: Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Protection
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "${{ github.event.action }}" == "opened" ]]; then
              if [[ "${{ github.base_ref }}" == "main" ]]; then
                echo "Branch protection enforced. You cannot push directly to the main branch."
                exit 1
              fi
            fi
          fi
